animations = ({
	triggers = ["open"];
	preset = "appear";
	scale = 0.4;
	duration = 0.2;
 }, {
	triggers = ["close"];
	preset = "disappear";
	scale = 0.5;
	duration = 0.15;
 }, {
 	triggers = ["show"];
	preset = "appear";
	scale = 0.4;
	duration = 0.2;
 }, {
 	triggers = ["hide"];
	preset = "disappear";
	scale = 0.5;
	duration = 0.15;
 }, {
 	triggers = ["geometry"];
	preset = "geometry-change";
	duration = 0.2;
})
