#!/bin/sh

# polybar y pipewire
/home/znorvik/.config/bspwm/pipewire-start.sh

# todo lo demas

sxhkd &
nm-applet &
feh --bg-fill ~/Descargas/wallhaven-pkrqe3.png &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config click_to_focus false
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
