#!/bin/sh

pipewire &
pipewire-pulse &
wireplumber &
sxhkd &
sleep 0.3 &&
polybar &
feh --bg-fill ~/dotfiles/wp4523638-zone-wallpapers.jpg &

bspc monitor -d I II III IV V VI VII VIII IX

bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.50
bspc config borderless_monocle   true
bspc config gapless_monocle      false

bspc config click_to_focus false
bspc config focus_follows_pointer true

# bspc rule -a Gimp desktop='^8' state=floating follow=on
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off
